<?php declare(strict_types=1);
/*
 * --------------------------------------------------------------------------------------------------------------------
 * <copyright company="Aspose" file="DataMatrixEncodeMode.php">
 *   Copyright (c) 2020 Aspose Pty Ltd
 * </copyright>
 * <summary>
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 * </summary>
 * --------------------------------------------------------------------------------------------------------------------
 */

/*
 *
 */
//
// This source code was auto-generated by AsposeBarcodeCloudCodegen.
//

namespace Aspose\BarCode\Model;

use Aspose\BarCode\ObjectSerializer;

/*
 * DataMatrixEncodeMode
 *
 * @description
 */
class DataMatrixEncodeMode
{

  /// <summary>
    /// Enum value Auto
    /// </summary>
    const Auto =  "Auto";
  
    /// <summary>
    /// Enum value ASCII
    /// </summary>
    const ASCII =  "ASCII";
  
    /// <summary>
    /// Enum value Full
    /// </summary>
    const Full =  "Full";
  
    /// <summary>
    /// Enum value Custom
    /// </summary>
    const Custom =  "Custom";
  
    /// <summary>
    /// Enum value C40
    /// </summary>
    const C40 =  "C40";
  
    /// <summary>
    /// Enum value Text
    /// </summary>
    const Text =  "Text";
  
    /// <summary>
    /// Enum value EDIFACT
    /// </summary>
    const EDIFACT =  "EDIFACT";
  
    /// <summary>
    /// Enum value ANSIX12
    /// </summary>
    const ANSIX12 =  "ANSIX12";
}
