<?php

declare(strict_types=1);
/*
 * --------------------------------------------------------------------------------------------------------------------
 * <copyright company="Aspose" file="ECIEncodings.php">
 *   Copyright (c) 2022 Aspose Pty Ltd
 * </copyright>
 * <summary>
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 * </summary>
 * --------------------------------------------------------------------------------------------------------------------
 */

/*
 *
 */
//
// This source code was auto-generated by AsposeBarcodeCloudCodegen.
//

namespace Aspose\BarCode\Model;

use Aspose\BarCode\ObjectSerializer;

/*
 * ECIEncodings
 *
 * @description
 */
class ECIEncodings
{
  /// <summary>
    /// Enum value NONE
    /// </summary>
    public const NONE =  "NONE";

    /// <summary>
    /// Enum value ISO_8859_1
    /// </summary>
    public const ISO_8859_1 =  "ISO_8859_1";

    /// <summary>
    /// Enum value ISO_8859_2
    /// </summary>
    public const ISO_8859_2 =  "ISO_8859_2";

    /// <summary>
    /// Enum value ISO_8859_3
    /// </summary>
    public const ISO_8859_3 =  "ISO_8859_3";

    /// <summary>
    /// Enum value ISO_8859_4
    /// </summary>
    public const ISO_8859_4 =  "ISO_8859_4";

    /// <summary>
    /// Enum value ISO_8859_5
    /// </summary>
    public const ISO_8859_5 =  "ISO_8859_5";

    /// <summary>
    /// Enum value ISO_8859_6
    /// </summary>
    public const ISO_8859_6 =  "ISO_8859_6";

    /// <summary>
    /// Enum value ISO_8859_7
    /// </summary>
    public const ISO_8859_7 =  "ISO_8859_7";

    /// <summary>
    /// Enum value ISO_8859_8
    /// </summary>
    public const ISO_8859_8 =  "ISO_8859_8";

    /// <summary>
    /// Enum value ISO_8859_9
    /// </summary>
    public const ISO_8859_9 =  "ISO_8859_9";

    /// <summary>
    /// Enum value ISO_8859_10
    /// </summary>
    public const ISO_8859_10 =  "ISO_8859_10";

    /// <summary>
    /// Enum value ISO_8859_11
    /// </summary>
    public const ISO_8859_11 =  "ISO_8859_11";

    /// <summary>
    /// Enum value ISO_8859_13
    /// </summary>
    public const ISO_8859_13 =  "ISO_8859_13";

    /// <summary>
    /// Enum value ISO_8859_14
    /// </summary>
    public const ISO_8859_14 =  "ISO_8859_14";

    /// <summary>
    /// Enum value ISO_8859_15
    /// </summary>
    public const ISO_8859_15 =  "ISO_8859_15";

    /// <summary>
    /// Enum value ISO_8859_16
    /// </summary>
    public const ISO_8859_16 =  "ISO_8859_16";

    /// <summary>
    /// Enum value Shift_JIS
    /// </summary>
    public const Shift_JIS =  "Shift_JIS";

    /// <summary>
    /// Enum value Win1250
    /// </summary>
    public const Win1250 =  "Win1250";

    /// <summary>
    /// Enum value Win1251
    /// </summary>
    public const Win1251 =  "Win1251";

    /// <summary>
    /// Enum value Win1252
    /// </summary>
    public const Win1252 =  "Win1252";

    /// <summary>
    /// Enum value Win1256
    /// </summary>
    public const Win1256 =  "Win1256";

    /// <summary>
    /// Enum value UTF16BE
    /// </summary>
    public const UTF16BE =  "UTF16BE";

    /// <summary>
    /// Enum value UTF8
    /// </summary>
    public const UTF8 =  "UTF8";

    /// <summary>
    /// Enum value US_ASCII
    /// </summary>
    public const US_ASCII =  "US_ASCII";

    /// <summary>
    /// Enum value Big5
    /// </summary>
    public const Big5 =  "Big5";

    /// <summary>
    /// Enum value GB18030
    /// </summary>
    public const GB18030 =  "GB18030";

    /// <summary>
    /// Enum value EUC_KR
    /// </summary>
    public const EUC_KR =  "EUC_KR";
}
