<?php

declare(strict_types=1);
/**
 * --------------------------------------------------------------------------------------------------------------------
 * <copyright company="Aspose" file="HanXinVersion.php">
 *   Copyright (c) 2024 Aspose Pty Ltd
 * </copyright>
 * <summary>
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 * </summary>
 * --------------------------------------------------------------------------------------------------------------------
 */

//
// This source code was auto-generated by AsposeBarcodeCloudCodegen.
//

namespace Aspose\BarCode\Model;

use Aspose\BarCode\ObjectSerializer;

/**
 * HanXinVersion
 *
 * @description
 */
class HanXinVersion
{
    /// <summary>
    /// Enum value Auto
    /// </summary>
    public const Auto =  "Auto";

    /// <summary>
    /// Enum value Version01
    /// </summary>
    public const Version01 =  "Version01";

    /// <summary>
    /// Enum value Version02
    /// </summary>
    public const Version02 =  "Version02";

    /// <summary>
    /// Enum value Version03
    /// </summary>
    public const Version03 =  "Version03";

    /// <summary>
    /// Enum value Version04
    /// </summary>
    public const Version04 =  "Version04";

    /// <summary>
    /// Enum value Version05
    /// </summary>
    public const Version05 =  "Version05";

    /// <summary>
    /// Enum value Version06
    /// </summary>
    public const Version06 =  "Version06";

    /// <summary>
    /// Enum value Version07
    /// </summary>
    public const Version07 =  "Version07";

    /// <summary>
    /// Enum value Version08
    /// </summary>
    public const Version08 =  "Version08";

    /// <summary>
    /// Enum value Version09
    /// </summary>
    public const Version09 =  "Version09";

    /// <summary>
    /// Enum value Version10
    /// </summary>
    public const Version10 =  "Version10";

    /// <summary>
    /// Enum value Version11
    /// </summary>
    public const Version11 =  "Version11";

    /// <summary>
    /// Enum value Version12
    /// </summary>
    public const Version12 =  "Version12";

    /// <summary>
    /// Enum value Version13
    /// </summary>
    public const Version13 =  "Version13";

    /// <summary>
    /// Enum value Version14
    /// </summary>
    public const Version14 =  "Version14";

    /// <summary>
    /// Enum value Version15
    /// </summary>
    public const Version15 =  "Version15";

    /// <summary>
    /// Enum value Version16
    /// </summary>
    public const Version16 =  "Version16";

    /// <summary>
    /// Enum value Version17
    /// </summary>
    public const Version17 =  "Version17";

    /// <summary>
    /// Enum value Version18
    /// </summary>
    public const Version18 =  "Version18";

    /// <summary>
    /// Enum value Version19
    /// </summary>
    public const Version19 =  "Version19";

    /// <summary>
    /// Enum value Version20
    /// </summary>
    public const Version20 =  "Version20";

    /// <summary>
    /// Enum value Version21
    /// </summary>
    public const Version21 =  "Version21";

    /// <summary>
    /// Enum value Version22
    /// </summary>
    public const Version22 =  "Version22";

    /// <summary>
    /// Enum value Version23
    /// </summary>
    public const Version23 =  "Version23";

    /// <summary>
    /// Enum value Version24
    /// </summary>
    public const Version24 =  "Version24";

    /// <summary>
    /// Enum value Version25
    /// </summary>
    public const Version25 =  "Version25";

    /// <summary>
    /// Enum value Version26
    /// </summary>
    public const Version26 =  "Version26";

    /// <summary>
    /// Enum value Version27
    /// </summary>
    public const Version27 =  "Version27";

    /// <summary>
    /// Enum value Version28
    /// </summary>
    public const Version28 =  "Version28";

    /// <summary>
    /// Enum value Version29
    /// </summary>
    public const Version29 =  "Version29";

    /// <summary>
    /// Enum value Version30
    /// </summary>
    public const Version30 =  "Version30";

    /// <summary>
    /// Enum value Version31
    /// </summary>
    public const Version31 =  "Version31";

    /// <summary>
    /// Enum value Version32
    /// </summary>
    public const Version32 =  "Version32";

    /// <summary>
    /// Enum value Version33
    /// </summary>
    public const Version33 =  "Version33";

    /// <summary>
    /// Enum value Version34
    /// </summary>
    public const Version34 =  "Version34";

    /// <summary>
    /// Enum value Version35
    /// </summary>
    public const Version35 =  "Version35";

    /// <summary>
    /// Enum value Version36
    /// </summary>
    public const Version36 =  "Version36";

    /// <summary>
    /// Enum value Version37
    /// </summary>
    public const Version37 =  "Version37";

    /// <summary>
    /// Enum value Version38
    /// </summary>
    public const Version38 =  "Version38";

    /// <summary>
    /// Enum value Version39
    /// </summary>
    public const Version39 =  "Version39";

    /// <summary>
    /// Enum value Version40
    /// </summary>
    public const Version40 =  "Version40";

    /// <summary>
    /// Enum value Version41
    /// </summary>
    public const Version41 =  "Version41";

    /// <summary>
    /// Enum value Version42
    /// </summary>
    public const Version42 =  "Version42";

    /// <summary>
    /// Enum value Version43
    /// </summary>
    public const Version43 =  "Version43";

    /// <summary>
    /// Enum value Version44
    /// </summary>
    public const Version44 =  "Version44";

    /// <summary>
    /// Enum value Version45
    /// </summary>
    public const Version45 =  "Version45";

    /// <summary>
    /// Enum value Version46
    /// </summary>
    public const Version46 =  "Version46";

    /// <summary>
    /// Enum value Version47
    /// </summary>
    public const Version47 =  "Version47";

    /// <summary>
    /// Enum value Version48
    /// </summary>
    public const Version48 =  "Version48";

    /// <summary>
    /// Enum value Version49
    /// </summary>
    public const Version49 =  "Version49";

    /// <summary>
    /// Enum value Version50
    /// </summary>
    public const Version50 =  "Version50";

    /// <summary>
    /// Enum value Version51
    /// </summary>
    public const Version51 =  "Version51";

    /// <summary>
    /// Enum value Version52
    /// </summary>
    public const Version52 =  "Version52";

    /// <summary>
    /// Enum value Version53
    /// </summary>
    public const Version53 =  "Version53";

    /// <summary>
    /// Enum value Version54
    /// </summary>
    public const Version54 =  "Version54";

    /// <summary>
    /// Enum value Version55
    /// </summary>
    public const Version55 =  "Version55";

    /// <summary>
    /// Enum value Version56
    /// </summary>
    public const Version56 =  "Version56";

    /// <summary>
    /// Enum value Version57
    /// </summary>
    public const Version57 =  "Version57";

    /// <summary>
    /// Enum value Version58
    /// </summary>
    public const Version58 =  "Version58";

    /// <summary>
    /// Enum value Version59
    /// </summary>
    public const Version59 =  "Version59";

    /// <summary>
    /// Enum value Version60
    /// </summary>
    public const Version60 =  "Version60";

    /// <summary>
    /// Enum value Version61
    /// </summary>
    public const Version61 =  "Version61";

    /// <summary>
    /// Enum value Version62
    /// </summary>
    public const Version62 =  "Version62";

    /// <summary>
    /// Enum value Version63
    /// </summary>
    public const Version63 =  "Version63";

    /// <summary>
    /// Enum value Version64
    /// </summary>
    public const Version64 =  "Version64";

    /// <summary>
    /// Enum value Version65
    /// </summary>
    public const Version65 =  "Version65";

    /// <summary>
    /// Enum value Version66
    /// </summary>
    public const Version66 =  "Version66";

    /// <summary>
    /// Enum value Version67
    /// </summary>
    public const Version67 =  "Version67";

    /// <summary>
    /// Enum value Version68
    /// </summary>
    public const Version68 =  "Version68";

    /// <summary>
    /// Enum value Version69
    /// </summary>
    public const Version69 =  "Version69";

    /// <summary>
    /// Enum value Version70
    /// </summary>
    public const Version70 =  "Version70";

    /// <summary>
    /// Enum value Version71
    /// </summary>
    public const Version71 =  "Version71";

    /// <summary>
    /// Enum value Version72
    /// </summary>
    public const Version72 =  "Version72";

    /// <summary>
    /// Enum value Version73
    /// </summary>
    public const Version73 =  "Version73";

    /// <summary>
    /// Enum value Version74
    /// </summary>
    public const Version74 =  "Version74";

    /// <summary>
    /// Enum value Version75
    /// </summary>
    public const Version75 =  "Version75";

    /// <summary>
    /// Enum value Version76
    /// </summary>
    public const Version76 =  "Version76";

    /// <summary>
    /// Enum value Version77
    /// </summary>
    public const Version77 =  "Version77";

    /// <summary>
    /// Enum value Version78
    /// </summary>
    public const Version78 =  "Version78";

    /// <summary>
    /// Enum value Version79
    /// </summary>
    public const Version79 =  "Version79";

    /// <summary>
    /// Enum value Version80
    /// </summary>
    public const Version80 =  "Version80";

    /// <summary>
    /// Enum value Version81
    /// </summary>
    public const Version81 =  "Version81";

    /// <summary>
    /// Enum value Version82
    /// </summary>
    public const Version82 =  "Version82";

    /// <summary>
    /// Enum value Version83
    /// </summary>
    public const Version83 =  "Version83";

    /// <summary>
    /// Enum value Version84
    /// </summary>
    public const Version84 =  "Version84";

}
