<?php

declare(strict_types=1);
/*
 * --------------------------------------------------------------------------------------------------------------------
 * <copyright company="Aspose" file="Pdf417ErrorLevel.php">
 *   Copyright (c) 2022 Aspose Pty Ltd
 * </copyright>
 * <summary>
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 * </summary>
 * --------------------------------------------------------------------------------------------------------------------
 */

/*
 *
 */
//
// This source code was auto-generated by AsposeBarcodeCloudCodegen.
//

namespace Aspose\BarCode\Model;

use Aspose\BarCode\ObjectSerializer;

/*
 * Pdf417ErrorLevel
 *
 * @description
 */
class Pdf417ErrorLevel
{
  /// <summary>
    /// Enum value Level0
    /// </summary>
    public const Level0 =  "Level0";

    /// <summary>
    /// Enum value Level1
    /// </summary>
    public const Level1 =  "Level1";

    /// <summary>
    /// Enum value Level2
    /// </summary>
    public const Level2 =  "Level2";

    /// <summary>
    /// Enum value Level3
    /// </summary>
    public const Level3 =  "Level3";

    /// <summary>
    /// Enum value Level4
    /// </summary>
    public const Level4 =  "Level4";

    /// <summary>
    /// Enum value Level5
    /// </summary>
    public const Level5 =  "Level5";

    /// <summary>
    /// Enum value Level6
    /// </summary>
    public const Level6 =  "Level6";

    /// <summary>
    /// Enum value Level7
    /// </summary>
    public const Level7 =  "Level7";

    /// <summary>
    /// Enum value Level8
    /// </summary>
    public const Level8 =  "Level8";
}
