<?php

declare(strict_types=1);
/*
 * --------------------------------------------------------------------------------------------------------------------
 * <copyright company="Aspose" file="QRVersion.php">
 *   Copyright (c) 2022 Aspose Pty Ltd
 * </copyright>
 * <summary>
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 * </summary>
 * --------------------------------------------------------------------------------------------------------------------
 */

/*
 *
 */
//
// This source code was auto-generated by AsposeBarcodeCloudCodegen.
//

namespace Aspose\BarCode\Model;

use Aspose\BarCode\ObjectSerializer;

/*
 * QRVersion
 *
 * @description
 */
class QRVersion
{
  /// <summary>
    /// Enum value Auto
    /// </summary>
    public const Auto =  "Auto";

    /// <summary>
    /// Enum value Version01
    /// </summary>
    public const Version01 =  "Version01";

    /// <summary>
    /// Enum value Version02
    /// </summary>
    public const Version02 =  "Version02";

    /// <summary>
    /// Enum value Version03
    /// </summary>
    public const Version03 =  "Version03";

    /// <summary>
    /// Enum value Version04
    /// </summary>
    public const Version04 =  "Version04";

    /// <summary>
    /// Enum value Version05
    /// </summary>
    public const Version05 =  "Version05";

    /// <summary>
    /// Enum value Version06
    /// </summary>
    public const Version06 =  "Version06";

    /// <summary>
    /// Enum value Version07
    /// </summary>
    public const Version07 =  "Version07";

    /// <summary>
    /// Enum value Version08
    /// </summary>
    public const Version08 =  "Version08";

    /// <summary>
    /// Enum value Version09
    /// </summary>
    public const Version09 =  "Version09";

    /// <summary>
    /// Enum value Version10
    /// </summary>
    public const Version10 =  "Version10";

    /// <summary>
    /// Enum value Version11
    /// </summary>
    public const Version11 =  "Version11";

    /// <summary>
    /// Enum value Version12
    /// </summary>
    public const Version12 =  "Version12";

    /// <summary>
    /// Enum value Version13
    /// </summary>
    public const Version13 =  "Version13";

    /// <summary>
    /// Enum value Version14
    /// </summary>
    public const Version14 =  "Version14";

    /// <summary>
    /// Enum value Version15
    /// </summary>
    public const Version15 =  "Version15";

    /// <summary>
    /// Enum value Version16
    /// </summary>
    public const Version16 =  "Version16";

    /// <summary>
    /// Enum value Version17
    /// </summary>
    public const Version17 =  "Version17";

    /// <summary>
    /// Enum value Version18
    /// </summary>
    public const Version18 =  "Version18";

    /// <summary>
    /// Enum value Version19
    /// </summary>
    public const Version19 =  "Version19";

    /// <summary>
    /// Enum value Version20
    /// </summary>
    public const Version20 =  "Version20";

    /// <summary>
    /// Enum value Version21
    /// </summary>
    public const Version21 =  "Version21";

    /// <summary>
    /// Enum value Version22
    /// </summary>
    public const Version22 =  "Version22";

    /// <summary>
    /// Enum value Version23
    /// </summary>
    public const Version23 =  "Version23";

    /// <summary>
    /// Enum value Version24
    /// </summary>
    public const Version24 =  "Version24";

    /// <summary>
    /// Enum value Version25
    /// </summary>
    public const Version25 =  "Version25";

    /// <summary>
    /// Enum value Version26
    /// </summary>
    public const Version26 =  "Version26";

    /// <summary>
    /// Enum value Version27
    /// </summary>
    public const Version27 =  "Version27";

    /// <summary>
    /// Enum value Version28
    /// </summary>
    public const Version28 =  "Version28";

    /// <summary>
    /// Enum value Version29
    /// </summary>
    public const Version29 =  "Version29";

    /// <summary>
    /// Enum value Version30
    /// </summary>
    public const Version30 =  "Version30";

    /// <summary>
    /// Enum value Version31
    /// </summary>
    public const Version31 =  "Version31";

    /// <summary>
    /// Enum value Version32
    /// </summary>
    public const Version32 =  "Version32";

    /// <summary>
    /// Enum value Version33
    /// </summary>
    public const Version33 =  "Version33";

    /// <summary>
    /// Enum value Version34
    /// </summary>
    public const Version34 =  "Version34";

    /// <summary>
    /// Enum value Version35
    /// </summary>
    public const Version35 =  "Version35";

    /// <summary>
    /// Enum value Version36
    /// </summary>
    public const Version36 =  "Version36";

    /// <summary>
    /// Enum value Version37
    /// </summary>
    public const Version37 =  "Version37";

    /// <summary>
    /// Enum value Version38
    /// </summary>
    public const Version38 =  "Version38";

    /// <summary>
    /// Enum value Version39
    /// </summary>
    public const Version39 =  "Version39";

    /// <summary>
    /// Enum value Version40
    /// </summary>
    public const Version40 =  "Version40";

    /// <summary>
    /// Enum value VersionM1
    /// </summary>
    public const VersionM1 =  "VersionM1";

    /// <summary>
    /// Enum value VersionM2
    /// </summary>
    public const VersionM2 =  "VersionM2";

    /// <summary>
    /// Enum value VersionM3
    /// </summary>
    public const VersionM3 =  "VersionM3";

    /// <summary>
    /// Enum value VersionM4
    /// </summary>
    public const VersionM4 =  "VersionM4";
}
