<?php
/*
 * --------------------------------------------------------------------------------------------------------------------
 * <copyright company="Aspose" file="QRVersion.php">
 *   Copyright (c) 2018 Aspose Pty Ltd
 * </copyright>
 * <summary>
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 * 
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 * 
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 * </summary>
 * --------------------------------------------------------------------------------------------------------------------
 */
/*
 * 
 */
//
// This source code was auto-generated by AsposeBarcodeCloudCodegen.
//

namespace Aspose\BarCode\Model;
use Aspose\BarCode\ObjectSerializer;

/*
 * QRVersion
 *
 * @description 
 */
class QRVersion
{

  /// <summary>
  /// Enum value Auto
  /// </summary>
  const Auto_ =  "Auto";
  
  /// <summary>
  /// Enum value Version01
  /// </summary>
  const Version01_ =  "Version01";
  
  /// <summary>
  /// Enum value Version02
  /// </summary>
  const Version02_ =  "Version02";
  
  /// <summary>
  /// Enum value Version03
  /// </summary>
  const Version03_ =  "Version03";
  
  /// <summary>
  /// Enum value Version04
  /// </summary>
  const Version04_ =  "Version04";
  
  /// <summary>
  /// Enum value Version05
  /// </summary>
  const Version05_ =  "Version05";
  
  /// <summary>
  /// Enum value Version06
  /// </summary>
  const Version06_ =  "Version06";
  
  /// <summary>
  /// Enum value Version07
  /// </summary>
  const Version07_ =  "Version07";
  
  /// <summary>
  /// Enum value Version08
  /// </summary>
  const Version08_ =  "Version08";
  
  /// <summary>
  /// Enum value Version09
  /// </summary>
  const Version09_ =  "Version09";
  
  /// <summary>
  /// Enum value Version10
  /// </summary>
  const Version10_ =  "Version10";
  
  /// <summary>
  /// Enum value Version11
  /// </summary>
  const Version11_ =  "Version11";
  
  /// <summary>
  /// Enum value Version12
  /// </summary>
  const Version12_ =  "Version12";
  
  /// <summary>
  /// Enum value Version13
  /// </summary>
  const Version13_ =  "Version13";
  
  /// <summary>
  /// Enum value Version14
  /// </summary>
  const Version14_ =  "Version14";
  
  /// <summary>
  /// Enum value Version15
  /// </summary>
  const Version15_ =  "Version15";
  
  /// <summary>
  /// Enum value Version16
  /// </summary>
  const Version16_ =  "Version16";
  
  /// <summary>
  /// Enum value Version17
  /// </summary>
  const Version17_ =  "Version17";
  
  /// <summary>
  /// Enum value Version18
  /// </summary>
  const Version18_ =  "Version18";
  
  /// <summary>
  /// Enum value Version19
  /// </summary>
  const Version19_ =  "Version19";
  
  /// <summary>
  /// Enum value Version20
  /// </summary>
  const Version20_ =  "Version20";
  
  /// <summary>
  /// Enum value Version21
  /// </summary>
  const Version21_ =  "Version21";
  
  /// <summary>
  /// Enum value Version22
  /// </summary>
  const Version22_ =  "Version22";
  
  /// <summary>
  /// Enum value Version23
  /// </summary>
  const Version23_ =  "Version23";
  
  /// <summary>
  /// Enum value Version24
  /// </summary>
  const Version24_ =  "Version24";
  
  /// <summary>
  /// Enum value Version25
  /// </summary>
  const Version25_ =  "Version25";
  
  /// <summary>
  /// Enum value Version26
  /// </summary>
  const Version26_ =  "Version26";
  
  /// <summary>
  /// Enum value Version27
  /// </summary>
  const Version27_ =  "Version27";
  
  /// <summary>
  /// Enum value Version28
  /// </summary>
  const Version28_ =  "Version28";
  
  /// <summary>
  /// Enum value Version29
  /// </summary>
  const Version29_ =  "Version29";
  
  /// <summary>
  /// Enum value Version30
  /// </summary>
  const Version30_ =  "Version30";
  
  /// <summary>
  /// Enum value Version31
  /// </summary>
  const Version31_ =  "Version31";
  
  /// <summary>
  /// Enum value Version32
  /// </summary>
  const Version32_ =  "Version32";
  
  /// <summary>
  /// Enum value Version33
  /// </summary>
  const Version33_ =  "Version33";
  
  /// <summary>
  /// Enum value Version34
  /// </summary>
  const Version34_ =  "Version34";
  
  /// <summary>
  /// Enum value Version35
  /// </summary>
  const Version35_ =  "Version35";
  
  /// <summary>
  /// Enum value Version36
  /// </summary>
  const Version36_ =  "Version36";
  
  /// <summary>
  /// Enum value Version37
  /// </summary>
  const Version37_ =  "Version37";
  
  /// <summary>
  /// Enum value Version38
  /// </summary>
  const Version38_ =  "Version38";
  
  /// <summary>
  /// Enum value Version39
  /// </summary>
  const Version39_ =  "Version39";
  
  /// <summary>
  /// Enum value Version40
  /// </summary>
  const Version40_ =  "Version40";
  
  /// <summary>
  /// Enum value VersionM1
  /// </summary>
  const VersionM1_ =  "VersionM1";
  
  /// <summary>
  /// Enum value VersionM2
  /// </summary>
  const VersionM2_ =  "VersionM2";
  
  /// <summary>
  /// Enum value VersionM3
  /// </summary>
  const VersionM3_ =  "VersionM3";
  
  /// <summary>
  /// Enum value VersionM4
  /// </summary>
  const VersionM4_ =  "VersionM4";
  
}

