<?php

/*
 * --------------------------------------------------------------------------------------------------------------------
 * <copyright company="Aspose" file="PutBarcodeRecognizeFromBodyRequest.php">
 *   Copyright (c) 2022 Aspose Pty Ltd
 * </copyright>
 * <summary>
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 * </summary>
 * --------------------------------------------------------------------------------------------------------------------
 */
//
// This source code was auto-generated by AsposeBarcodeCloudCodegen.
//

declare(strict_types=1);

namespace Aspose\BarCode\Requests;

/*
 * Request model for "putBarcodeRecognizeFromBody" operation.
 */
class PutBarcodeRecognizeFromBodyRequest
{
    /*
     * Initializes a new instance of the PutBarcodeRecognizeFromBodyRequest class.
     *
     * @param string $name The image file name.
     * @param \Aspose\BarCode\Model\ReaderParams $reader_params BarcodeReader object with parameters.
     * @param string $type
     * @param string $storage The storage name
     * @param string $folder The image folder.
     */
    public function __construct($name, $reader_params, $type = null, $storage = null, $folder = null)
    {
        $this->name = $name;
        $this->reader_params = $reader_params;
        $this->type = $type;
        $this->storage = $storage;
        $this->folder = $folder;
    }

    /*
     * The image file name.
     */
    public $name;

    /*
     * BarcodeReader object with parameters.
     */
    public $reader_params;

    /*
     * Gets or sets type
     */
    public $type;

    /*
     * The storage name
     */
    public $storage;

    /*
     * The image folder.
     */
    public $folder;
}
